# Generated by Django 4.1.9 on 2023-11-20 11:20

from django.db import migrations, models
import file_versions.models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="url",
            field=models.CharField(default="/documents/reviews", max_length=512),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="file",
            field=models.FileField(upload_to=file_versions.models.get_upload_path),
        ),
    ]
