# Generated by Django 4.1.9 on 2023-11-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_fileversion_url_alter_fileversion_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="url",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
