# Generated by Django 4.1.9 on 2023-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0005_alter_fileversion_version_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileversion",
            old_name="url",
            new_name="file_path",
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="file",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file_path", "version_number")},
        ),
    ]
