# Generated by Django 4.1.9 on 2023-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0006_rename_url_fileversion_file_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
