# Generated by Django 4.1.9 on 2023-11-23 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_versions", "0008_fileversion_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file_path", "version_number", "user")},
        ),
    ]
